# Generated by Django 5.0.6 on 2026-03-11 06:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="fixture",
            name="fixture_id",
            field=models.CharField(max_length=40, null=True, unique=True),
        ),
    ]
