# Generated by Django 5.0.6 on 2026-03-11 06:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0002_fixture_fixture_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="fixture",
            name="id",
        ),
        migrations.AlterField(
            model_name="fixture",
            name="fixture_id",
            field=models.CharField(
                max_length=40, primary_key=True, serialize=False, unique=True
            ),
        ),
    ]
