# Generated by Django 5.0.6 on 2026-06-22 13:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0003_remove_fixture_id_alter_fixture_fixture_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="fixture",
            name="away_win_probability",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="fixture",
            name="draw_probability",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="fixture",
            name="home_win_probability",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name="fixture",
            index=models.Index(
                fields=["home_team", "away_team", "league"],
                name="main_fixtur_home_te_1724b1_idx",
            ),
        ),
    ]
